# Generated by Django 3.0 on 2020-10-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
