# Generated by Django 3.0 on 2020-10-24 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_category_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='amount',
        ),
    ]
